### ISSUE TITLE
shady dependency "rollup-plugin-resolve"

### ISSUE THREAD

**Issue by justlep** [composor/hyperx-es6#1]
Through a typo, I accidentally installed the "rollup-plugin-resolve" package (instead of "rollup-plugin-node-resolve"), then noticed it's basically an empty, undocumented npm package, with hyperx-es6 being the only known dependent (according to https://www.npmjs.com/package/rollup-plugin-resolve).

Maybe you, too, installed it by mistake and might rather want to remove it from your dependencies?

**Comment by rbiggs** [comment]
Thanks. That's a giblet alright. It was used as a bridge way back between rollup and Babel due to some issues. Regardless, it wasn't supposed to be a dependency. I have to update this anyways to use Gulp 4.
